### PR TITLE
Add support for filtering server via labels

### PR DESCRIPTION
**Pull request by mwarkentin**
This pull request adds support for filtering servers by their labels, as per https://rpm.newrelic.com/api/explore/servers/list

### CODE REVIEW

**Comment by micahhausler** [comment]
@mwarkentin Thank you for opening this! This would be a great feature. Do you mind making the `filter_labels` param a dictionary? The key/values could be joined like:
```python
['{}:{}'.format(label, value) for label, value in filter_labels.items()]
```

**Comment by mwarkentin** [comment]
@micahhausler Sure, so the param would be a dict, where `key` is the type, and `value` is the value?

```python
response = self.server.list(filter_labels={'Type1': 'Value1', 'Type2': 'Value2'})
```

**Comment by micahhausler** [comment]
Yep! And if you could add that note in the method docstring that'd be great!

**Comment by mwarkentin** [comment]
@micahhausler Sorry for the commit spam, but this should be working now.

**Comment by micahhausler** [comment]
Looks great! Thanks! :+1:

**Comment by mwarkentin** [comment]
Awesome, thank you!

**Pull request merged**
